(function(){
  if(!window.UCAPI)return;
  OWNER_EVENTS=[];OWNER_TRASH=[];
  evTime=e=>String(e.date||"")+" "+String(e.start||e.gather||"");
  filteredEvents=()=>{const q=(document.getElementById("evSearch").value||"").toLowerCase(),d=document.getElementById("evDate").value,st=document.getElementById("evStatus").value;return OWNER_EVENTS.filter(e=>{const hay=[e.title,e.place,e.instructor,e.note].join(" ").toLowerCase();if(q&&!hay.includes(q))return false;if(d&&e.date!==d)return false;if(st==="cancelled"&&!e.cancelled)return false;if(st==="done"&&!e.done)return false;if(st==="active"&&(e.done||e.cancelled))return false;return true}).sort((a,b)=>evTime(a).localeCompare(evTime(b)))};
  drawOwnerEvents=()=>{const box=document.getElementById("eventList"),a=filteredEvents();box.innerHTML=a.length?a.slice(0,150).map(e=>`<div class="row"><div><b>${esc(e.title||"Занятие")}</b><div class="meta">${esc(evTime(e))} · ${esc(e.place||"—")}</div><div class="meta">${esc(e.instructor||"—")} · ${e.cancelled?"ОТМЕНЕНО":e.done?"ЗАВЕРШЕНО":"активно"}</div></div></div>`).join(""):"<p class='hint'>Ничего не найдено.</p>"};
  drawCancelled=()=>{const box=document.getElementById("cancelList"),a=OWNER_EVENTS.filter(e=>e.cancelled);box.innerHTML=a.length?a.map(e=>`<div class="row"><div><b>${esc(e.title||"Занятие")}</b><div class="meta">${esc(evTime(e))} · ${esc(e.instructor||"—")}</div><div class="meta">Причина: ${esc(e.cancelReason||"—")}</div></div></div>`).join(""):"<p class='hint'>Отменённых занятий нет.</p>"};
  showInstructor=login=>{const u=LIST.find(x=>x.login===login),name=u?((u.last||"")+" "+(u.first||"")).trim():login,q=(name||login||"").toLowerCase(),a=OWNER_EVENTS.filter(e=>String(e.instructor||"").toLowerCase().includes(q)||String(e.createdBy||"").toLowerCase()===String(login||"").toLowerCase()),cancel=a.filter(e=>e.cancelled).length,done=a.filter(e=>e.done).length;alert((name||login)+"\nВсего занятий: "+a.length+"\nЗавершено: "+done+"\nОтменено: "+cancel+"\nАктивных: "+(a.length-done-cancel))};
  function mapUser(u){return{login:u.login,first:u.first||"",last:u.last||"",role:u.role,blocked:!!u.blocked,canDelete:u.role==="owner"||u.role==="admin",lastSeen:u.lastSeenAt||""}}
  gh=async()=>{throw new Error("Прямой доступ к GitHub отключён")};
  loadUsers=async()=>{const d=await UCAPI.users();LIST=d.users.map(mapUser);BANS=[];draw();setStatus("Пользователей: "+LIST.length);await loadDashboard();await loadOwnerEvents();};
  loadOwnerEvents=async()=>{const d=await UCAPI.schedule();OWNER_EVENTS=d.events||[];OWNER_TRASH=d.trash||[];drawOwnerEvents();drawAudit();drawCancelled();};
  loadDashboard=async()=>{const d=await UCAPI.dashboard(), el=document.getElementById("summary");if(el)el.innerHTML=`<div class="stat"><b>${d.today}</b><span>Сегодня</span></div><div class="stat"><b>${d.upcoming}</b><span>Предстоящие</span></div><div class="stat"><b>${d.cancelled}</b><span>Отменённые</span></div>`;const ds=document.getElementById("dsState");if(ds)ds.textContent=`Discord: отправлено ${d.discord.sent} · удалено ${d.discord.deleted} · ошибок ${d.discord.errors} · проверка ${d.discord.lastChecked?when(d.discord.lastChecked):"—"}`;};
  drawAudit=async()=>{const box=document.getElementById("auditList");if(!box)return;try{const d=await UCAPI.audit();box.innerHTML=d.entries.length?d.entries.map(x=>`<div class="row"><div><b>${esc(x.action)}</b> · ${esc(x.target_id)}<div class="meta">${when(x.at)} · ${esc(x.actor)}${x.details?" · "+esc(x.details):""}</div></div></div>`).join(""):"Журнал пока пуст."}catch(e){box.textContent=e.message}};
  loadTrash=async()=>{const d=await UCAPI.schedule();OWNER_TRASH=d.trash||[];const box=document.getElementById("trashList");box.innerHTML=OWNER_TRASH.length?OWNER_TRASH.map(ev=>`<div class="row"><div><b>${esc(ev.title||"Занятие")}</b><div class="meta">${esc(evLine(ev))}</div></div><button type="button" class="ghost" data-restore="${esc(ev.id)}">Вернуть</button></div>`).join(""):"<p class='hint'>Корзина пустая.</p>";box.querySelectorAll("[data-restore]").forEach(b=>b.onclick=()=>restoreEv(b.dataset.restore));};
  restoreEv=async id=>{try{await UCAPI.restoreEvent(id);setStatus("Занятие восстановлено");await loadTrash();await loadOwnerEvents()}catch(e){setStatus(e.message)}};
  toggle=async login=>{const u=LIST.find(x=>x.login===login);try{await UCAPI.updateUser(login,{role:u.role==="admin"?"instructor":"admin"});await loadUsers()}catch(e){setStatus(e.message)}};
  setPass=async login=>{const inp=document.querySelector('input[data-pw="'+login+'"]'),password=inp?inp.value:"";if(password.length<10){alert("Новый пароль — минимум 10 символов");return}try{await UCAPI.updateUser(login,{password});inp.value="";setStatus("Пароль обновлён")}catch(e){setStatus(e.message)}};
  blockUser=async login=>{const u=LIST.find(x=>x.login===login);try{await UCAPI.updateUser(login,{blocked:!u.blocked});await loadUsers()}catch(e){setStatus(e.message)}};
  removeUser=async login=>{if(!confirm("Удалить пользователя "+login+"?"))return;try{await UCAPI.deleteUser(login);await loadUsers()}catch(e){setStatus(e.message)}};
  banUserDevice=async()=>alert("Блокировка устройств заменена серверными сессиями и блокировкой аккаунта.");unban=banUserDevice;
  document.getElementById("enter").onclick=async()=>{try{const d=await UCAPI.login("owner",document.getElementById("pin").value);await ucRequirePasswordChange(d.user);document.getElementById("gate").hidden=true;document.getElementById("app").hidden=false;await loadUsers();await loadTrash()}catch(e){alert(e.message)}};
  document.getElementById("ownerSave").onclick=async()=>{const a=document.getElementById("ownerNew").value,b=document.getElementById("ownerNew2").value;if(a.length<10){alert("Пароль минимум 10 символов");return}if(a!==b){alert("Пароли не совпали");return}try{await UCAPI.updateUser("owner",{password:a});document.getElementById("ownerNew").value="";document.getElementById("ownerNew2").value="";setStatus("Пароль owner обновлён")}catch(e){setStatus(e.message)}};
  loadDiscordDetail=loadDashboard;
  downloadBackup=async()=>{const [s,u,a]=await Promise.all([UCAPI.schedule(),UCAPI.users(),UCAPI.audit()]);const blob=new Blob([JSON.stringify({created:new Date().toISOString(),schedule:s,users:u,audit:a},null,2)],{type:"application/json"}),x=document.createElement("a");x.href=URL.createObjectURL(blob);x.download="uc-backup-"+new Date().toISOString().slice(0,10)+".json";x.click();setTimeout(()=>URL.revokeObjectURL(x.href),1000)};
})();
