const URL=Deno.env.get('SUPABASE_URL')!;
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const PUBLIC=Deno.env.get('SUPABASE_ANON_KEY')!;
const ORIGINS=new Set(['https://tophik2345.github.io','http://localhost:4173','http://127.0.0.1:4173']);
class ApiError extends Error{status:number;constructor(message:string,status=400){super(message);this.status=status}}
async function rpc(name:string,data:any){const r=await fetch(`${URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json().catch(()=>null);if(!r.ok)throw new ApiError(j?.message||'Ошибка базы');return j}
async function auth(path:string,body:any,token=KEY,method='POST'){const r=await fetch(`${URL}/auth/v1/${path}`,{method,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok){const raw=j?.msg||j?.message||j?.error_description||'';const fallback=path.startsWith('token')?'Неверный логин или пароль':'Не удалось выполнить действие с аккаунтом';throw new ApiError(raw||fallback,r.status===401?401:r.status===429?429:400)}return j}
const norm=(v:any)=>String(v??'').trim().toLowerCase();
const hex=(v:string)=>Array.from(new TextEncoder().encode(v),b=>b.toString(16).padStart(2,'0')).join('');
const oldEmail=(login:string)=>`u-${hex(login)}@accounts.uc-schedule.invalid`;
const brokenEmail=(login:string)=>`u-${hex(login)}@example.com`;
const newEmail=(login:string)=>`u-${hex(login)}@hpeqnqsgcqskjpdjkxcm.supabase.co`;
const validPass=(p:any)=>{if(typeof p!=='string'||p.length<12||new TextEncoder().encode(p).length>72)throw new ApiError('Пароль: от 12 символов, не более 72 байт');return p};
const claims=(t:string)=>JSON.parse(atob(t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(t.split('.')[1].length/4)*4,'=')));
Deno.serve(async req=>{const origin=req.headers.get('Origin')||'';const headers:any={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin'};if(ORIGINS.has(origin))Object.assign(headers,{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST,OPTIONS'});const reply=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers});if(origin&&!ORIGINS.has(origin))return reply({error:'Источник запроса не разрешён'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return reply({error:'Метод не поддерживается'},405);try{const {action,input={}}=await req.json();if(action==='register'){const login=norm(input.login);if(!/^[a-z0-9_.-]{3,32}$/.test(login))throw new ApiError('Логин: 3–32 латинских буквы, цифры, точка, дефис или подчёркивание');validPass(input.password);const first=String(input.first||'').trim(),last=String(input.last||'').trim();if(!first||!last||first.length>60||last.length>60)throw new ApiError('Введите имя и фамилию');if(!await rpc('uc_gate',{p_key:'register:global',p_limit:50,p_seconds:3600})||!await rpc('uc_gate',{p_key:`register:${login}`,p_limit:5,p_seconds:900}))throw new ApiError('Слишком много попыток регистрации. Попробуйте позже',429);if(!await rpc('uc_registration',{p_login:login,p_code:String(input.code||'')}))throw new ApiError('Неверный спецпароль или логин уже занят');const user=await auth('admin/users',{email:newEmail(login),password:input.password,email_confirm:true});try{await rpc('uc_attach',{p_id:user.id,p_login:login,p_first:first,p_last:last})}catch(e){await auth(`admin/users/${user.id}`,undefined,KEY,'DELETE').catch(()=>{});throw e}return reply({ok:true})}
if(action==='login'){const login=norm(input.login);if(!/^[a-zа-яё0-9_.-]{2,32}$/i.test(login))throw new ApiError('Неверный логин или пароль',401);if(!await rpc('uc_gate',{p_key:`login:${login}`,p_limit:12,p_seconds:900}))throw new ApiError('Слишком много попыток. Подождите 15 минут',429);let session:any=null,last:any;for(const email of [oldEmail(login),brokenEmail(login),newEmail(login)]){try{session=await auth('token?grant_type=password',{email,password:input.password},PUBLIC);break}catch(e){last=e}}if(!session)throw last||new ApiError('Неверный логин или пароль',401);const c=claims(session.access_token);const me=await rpc('uc_action',{p_actor:session.user.id,p_session:c.session_id,p_action:'session.open',p_input:{device:input.device}});return reply({session:{access_token:session.access_token,refresh_token:session.refresh_token,expires_at:Math.floor(Date.now()/1000)+session.expires_in},me})}
throw new ApiError('Неизвестное действие',404)}catch(e){return reply({error:e instanceof ApiError?e.message:'Ошибка сервера'},e instanceof ApiError?e.status:400)}});
